language: python
os: linux
env:
  - QT_QPA_PLATFORM="offscreen"
matrix:
  include:
    # ===== Linux =====
    - name: "Xenial with Python 3.7"
      dist: xenial
      python: 3.7
    - name: "Xenial with Python 3.8"
      dist: xenial
      python: 3.8
    - name: "Bionic with Python 3.7"
      dist: bionic
      python: 3.7
    - name: "Bionic with Python 3.8"
      dist: bionic
      python: 3.8
    - name: "Focal with Python 3.7"
      dist: focal
      python: 3.7
      sudo: required
    - name: "Focal with Python 3.8"
      dist: focal
      python: 3.8
    # ===== OSX =====
    - name: "Python 3.7.5 on macOS 10.14"
      os: osx
      osx_image: xcode10.2  # Python 3.7.5 running on macOS 10.14.3
      language: shell
    - name: "Python 3.8.0 on macOS 10.14"
      os: osx
      osx_image: xcode11.3  # Python 3.8.0 running on macOS 10.14.6
      language: shell
      # ===== Windows =====
    - name: "Python 3.7.8 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.8
        - python -m pip install --upgrade pip
      script:
        - python -m unittest tests/test_date.py
        - python -m unittest tests/test_data.py
        - python -m unittest tests/test_log_win.py
        - python -m unittest tests/test_edit_log_win.py
        - python -m unittest tests/test_fd_win.py
        - python -m unittest tests/test_edit_fd_win.py
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.8.5 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.5
        - python -m pip install --upgrade pip
      script:
        - python -m unittest tests/test_date.py
        - python -m unittest tests/test_data.py
        - python -m unittest tests/test_log_win.py
        - python -m unittest tests/test_edit_log_win.py
        - python -m unittest tests/test_fd_win.py
        - python -m unittest tests/test_edit_fd_win.py
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
before_install:
  - pip3 install --upgrade pip
install:
  - pip3 install .
script:
  # Running the tests collectively results in a segmentation fault,
  # which I can't seem to resolve. The test files are therefore run separately.
  - python3 -m unittest tests/test_date.py
  - python3 -m unittest tests/test_data.py
  - python3 -m unittest tests/test_log_win.py
  - python3 -m unittest tests/test_edit_log_win.py
  - python3 -m unittest tests/test_fd_win.py
  - python3 -m unittest tests/test_edit_fd_win.py
